language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-rbpmod' ]; then cd .. && eval "mv $currentfolder generator-rbpmod" && cd generator-rbpmod; fi
